name: Readme Template
on:
  schedule:
    - cron: '0 */2 * * *' # every 2 hours
  push:
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Generate README.md
      uses: probablykasper/readme-template-action@v1
      with:
#         token: ${{ secrets.README_TEMPLATE_TOKEN }}
        template: TEMPLATE.md
        output: GENERATED.md
      - name: Commit any changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Data updated"
          push_options: --force
